name: eng-annotations
concurrency:
  group: eng-annotations
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  Notify:
    uses: ./.github/workflows/notify.yml
    with:
      cache_key: eng_annotations
      slack_channel_id: ${{ vars.ENG_ANNOTATIONS_SLACK_CHANNEL_ID }}
    secrets:
      SEARCH_PARAMS: '{"group": "${{ secrets.ENG_ANNOTATIONS_HYPOTHESIS_GROUP }}"}'
      HYPOTHESIS_API_TOKEN: ${{ secrets.HYPOTHESIS_API_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  Snitch:
    needs: Notify
    runs-on: ubuntu-latest
    steps:
      - run: curl https://nosnch.in/${{ secrets.ENG_ANNOTATIONS_SNITCH_ID }}
