name: Notify
on:
  workflow_dispatch:
jobs:
  Alert:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install pipx
        run: python -m pip install pipx
      - name: Checkout slack-annotations
        uses: actions/checkout@v4
      - name: Install slack-annotations
        run: python -m pipx install .
      - name: Check for annotations
        id: slack_message
        run: |
          {
            echo 'SLACK_MESSAGE<<EOF'
            slack-annotations --group ${{ secrets.GROUP }} --token ${{ secrets.TOKEN }}
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ vars.SLACK_CHANNEL }}
          slack-message: ${{ env.SLACK_MESSAGE }}
        env:
          SLACK_MESSAGE: ${{ steps.slack_message.outputs.SLACK_MESSAGE }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
