name: Notify
concurrency:
  group: notify
on:
  workflow_call:
    inputs:
      cache_key:
        required: true
        type: string
      slack_channel_id:
        required: true
        type: string
    secrets:
      SEARCH_PARAMS:
        required: false
      HYPOTHESIS_API_TOKEN:
        required: false
      SLACK_BOT_TOKEN:
        required: true
jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          key: cache-${{ inputs.cache_key }}-${{ github.run_number }}
          path: ~/.cache.json
          restore-keys: |
            cache-${{ inputs.cache_key }}-
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install pipx
        run: python -m pip install pipx
      - name: Checkout slack-annotations
        uses: actions/checkout@v4
      - name: Install slack-annotations
        run: python -m pipx install .
      - name: Check for annotations
        id: slack_message
        run: |
          {
            echo 'SLACK_MESSAGE<<EOF'
            slack-annotations \
              --search-params '${{ secrets.SEARCH_PARAMS }}' \
              --token '${{ secrets.HYPOTHESIS_API_TOKEN }}' \
              --cache-path ~/.cache.json
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          payload: ${{ env.SLACK_MESSAGE }}
        env:
          SLACK_MESSAGE: ${{ steps.slack_message.outputs.SLACK_MESSAGE }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: steps.slack_message.outputs.SLACK_MESSAGE
