name: pr-website
concurrency:
  group: pr-website
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  Notify:
    uses: ./.github/workflows/notify.yml
    with:
      cache_key: pr_website
      slack_channel_id: ${{ vars.PR_WEBSITE_SLACK_CHANNEL_ID }}
    secrets:
      SEARCH_PARAMS: '{"wildcard_uri": ["https://web.hypothes.is/*", "https://hypothes.is/*"]}'
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  Snitch:
    needs: Notify
    runs-on: ubuntu-latest
    steps:
      - run: curl https://nosnch.in/${{ secrets.PR_WEBSITE_SNITCH_ID }}
