name: support-kb
concurrency:
  group: support-kb
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  Notify:
    uses: ./.github/workflows/notify.yml
    with:
      cache_key: support-kb
      slack_channel_id: ${{ vars.SUPPORT_KB_SLACK_CHANNEL_ID }}
      group_name: ${{ vars.SUPPORT_KB_GROUP_NAME }}
    secrets:
      SEARCH_PARAMS: ${{ secrets.SUPPORT_KB_SEARCH_PARAMS }}
      HYPOTHESIS_API_TOKEN: ${{ secrets.HYPOTHESIS_API_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  Snitch:
    needs: Notify
    runs-on: ubuntu-latest
    steps:
      - run: curl https://nosnch.in/${{ secrets.SUPPORT_KB_SNITCH_ID }}
